function feat_default = define_feat_default

feat_default  = {'ratio_nuclear';...
                 'Ripley_max'; ...
                 'Ripley_gradient_max';...
                 'Ripley_gradient_min';...
                 'Ripley_mid_cell';...
                 'Ripley_corr';...
                 'Ripley_dist_max';...
                 'polarization_index';...
                 'dispersion_index';...
                 'morph_opening_15_ratio';...
                 'morph_opening_30_ratio';...
                 'morph_opening_45_ratio';...
                 'morph_opening_60_ratio';...
                 'cell_heigth_Spearman';...
                 'cell_heigth_rsquared';...
                 'dist_cell_membrane_mean';...
                 'dist_cell_membrane_q5';...
                 'dist_cell_membrane_q10';...
                 'dist_cell_membrane_q20';...
                 'dist_cell_membrane_q50';...
                 'dist_nuc_membrane_mean';...
                 'dist_cell_centroid_mean';... 
                 'dist_nucleus_centroid_mean'};